name: todo_app
description: A complete Flutter Todo App with CRUD operations, categories, search, and themes.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.2.2

  # UUID Generation
  uuid: ^4.1.0

  # Date Formatting
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true